meta_product_name: "Kitchen Cart"
meta_title: "Kitchen Cart – Find Food Carts Near You"
meta_description: "Kitchen Cart helps you find food carts near you."
meta_image: "cover.png" # located in `app/assets/images/`
twitter_account: "@worksofgenius"   # required for Twitter Cards